const fs = require('fs');
const path = require('path');

const dataDir = process.env.DATA_DIR || path.join(__dirname, '..', '..');

if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

const dbPath = path.join(dataDir, 'database.json');

const defaultData = {
  users: {},
  items: {
    'sprite': {
      id: 'sprite',
      name: 'Sprite',
      price: 90,
      emoji: '<:Sprite:1520045436805714040>',
      menuEmoji: '🥤',
      description: 'Refresco de lima-limón bien frío. Perfecto para refrescarse entre partidas.',
      stock: 500,
      maxStock: 500,
      category: 'refresco',
      usable: true,
      sellable: true,
      sellPrice: 54,
      useMessage: 'Te bebes la Sprite de un trago. El burbujeo te recuerda que estás vivo y con gases.'
    },
    'cocacola': {
      id: 'cocacola',
      name: 'Coca-Cola',
      price: 100,
      emoji: '<:CocaCola:1520045243758674041>',
      menuEmoji: '🥤',
      description: 'El clásico de toda la vida. Siempre hay alguien que pide una.',
      stock: 500,
      maxStock: 500,
      category: 'refresco',
      usable: true,
      sellable: true,
      sellPrice: 60,
      useMessage: 'Destapas la Coca-Cola y el sonido te transporta a tu infancia. O a la resaca que te espera.'
    },
    'nestea_maracuya': {
      id: 'nestea_maracuya',
      name: 'Nestea Maracuyá',
      price: 140,
      emoji: '<:NesteaMaracuya:1520045119921717299>',
      menuEmoji: '🧃',
      description: 'Té frío con un toque tropical de maracuyá. Dulce y refrescante.',
      stock: 250,
      maxStock: 250,
      category: 'refresco',
      usable: true,
      sellable: true,
      sellPrice: 84,
      useMessage: 'Bebes el Nestea de Maracuyá y sientes el trópico en la garganta. Instante de felicidad.'
    },
    'aquarius_melocoton': {
      id: 'aquarius_melocoton',
      name: 'Aquarius Melocotón',
      price: 120,
      emoji: '<:AquariusMelocoton:1520044944448815164>',
      menuEmoji: '🧃',
      description: 'Bebida isotónica sabor melocotón para recuperar energía.',
      stock: 300,
      maxStock: 300,
      category: 'refresco',
      usable: true,
      sellable: true,
      sellPrice: 72,
      useMessage: 'Te hidratas con Aquarius Melocotón. Vuelves a sentirte humano.'
    },
    'aquarius_naranja': {
      id: 'aquarius_naranja',
      name: 'Aquarius Naranja',
      price: 120,
      emoji: '<:AquariusNaranja:1520044811619406054>',
      menuEmoji: '🧃',
      description: 'Isotónica de naranja con un sabor ligero y cítrico.',
      stock: 300,
      maxStock: 300,
      category: 'refresco',
      usable: true,
      sellable: true,
      sellPrice: 72,
      useMessage: 'El Aquarius de Naranja entra suave. Tus electrolitos te lo agradecen.'
    },
    'fanta_naranja': {
      id: 'fanta_naranja',
      name: 'Fanta Naranja',
      price: 100,
      emoji: '<:FantaNaranja:1520044604232040579>',
      menuEmoji: '🥤',
      description: 'Refresco de naranja con burbujas y mucho azúcar. La receta de la felicidad temporal.',
      stock: 450,
      maxStock: 450,
      category: 'refresco',
      usable: true,
      sellable: true,
      sellPrice: 60,
      useMessage: 'La Fanta Naranja explota en tu boca. Azúcar pura, felicidad inmediata.'
    },
    'fanta_limon': {
      id: 'fanta_limon',
      name: 'Fanta Limón',
      price: 100,
      emoji: '<:FantaLimon:1520044475324305558>',
      menuEmoji: '🥤',
      description: 'Refresco cítrico con un punto ácido muy refrescante.',
      stock: 450,
      maxStock: 450,
      category: 'refresco',
      usable: true,
      sellable: true,
      sellPrice: 60,
      useMessage: 'El fresco de Limón recorre tu garganta como una brisa de cubierta. Perfecto.'
    },
    'aquarius_limon': {
      id: 'aquarius_limon',
      name: 'Aquarius Limón',
      price: 120,
      emoji: '<:AquariusLimon:1520044298240917628>',
      menuEmoji: '🧃',
      description: 'Bebida isotónica de limón, ideal para hidratarse en cubierta.',
      stock: 300,
      maxStock: 300,
      category: 'refresco',
      usable: true,
      sellable: true,
      sellPrice: 72,
      useMessage: 'Bebes el Aquarius Limón. Te rehidratas como si hubieras corrido un maratón. No lo has hecho.'
    },
    'daiquiri': {
      id: 'daiquiri',
      name: 'Daiquiri',
      price: 550,
      emoji: '<:Daiquiri:1520043379797266452>',
      menuEmoji: '🍹',
      description: 'Cóctel afrutado preparado con ron y zumo de lima.',
      stock: 60,
      maxStock: 60,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 330,
      useMessage: 'Sorbes el Daiquiri y el ron te calienta el pecho. La lima te despierta. Perfecto equilibrio.'
    },
    'margarita': {
      id: 'margarita',
      name: 'Margarita',
      price: 650,
      emoji: '<:Margarita:1520043277292929114>',
      menuEmoji: '🍸',
      description: 'El clásico mexicano con tequila y lima. Un imprescindible.',
      stock: 50,
      maxStock: 50,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 390,
      useMessage: 'La sal del borde, el tequila en la lengua. La Margarita es pura poesía líquida.'
    },
    'caipirinha': {
      id: 'caipirinha',
      name: 'Caipirinha',
      price: 700,
      emoji: '<:Caipirinha:1520043159114223727>',
      menuEmoji: '🥃',
      description: 'Cóctel brasileño de cachaça, lima y azúcar de caña.',
      stock: 45,
      maxStock: 45,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 420,
      useMessage: 'Bebes la Caipirinha. Brasil te abraza en forma de cachaça y lima.'
    },
    'pina_colada': {
      id: 'pina_colada',
      name: 'Piña Colada',
      price: 800,
      emoji: '<:PinaColada:1520042823095685160>',
      menuEmoji: '🥥',
      description: 'Mezcla cremosa de piña, coco y ron. Sabe a vacaciones.',
      stock: 40,
      maxStock: 40,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 480,
      useMessage: 'La Piña Colada es un abrazo tropical. Coco, piña y la promesa de una siesta.'
    },
    'mojito': {
      id: 'mojito',
      name: 'Mojito',
      price: 750,
      emoji: '<:Mohito:1520042750106402967>',
      menuEmoji: '🍃',
      description: 'Ron blanco, hierbabuena, lima y un toque de soda. El favorito de media humanidad.',
      stock: 45,
      maxStock: 45,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 450,
      useMessage: 'El Mojito te golpea con hierbabuena fresca. Cada sorbo sabe a verano en cubierta.'
    },
    'daiquiri_sa': {
      id: 'daiquiri_sa',
      name: 'Daiquiri (Sin Alcohol)',
      price: 350,
      emoji: '<:Daiquiri:1520043379797266452>',
      menuEmoji: '🍹',
      description: 'La misma fruta, menos remordimiento. Para conductores de lancha y responsables.',
      stock: 120,
      maxStock: 120,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 210,
      useMessage: 'El Daiquiri sin alcohol sabe a fruta y a buenas decisiones. Quién lo diría.'
    },
    'margarita_sa': {
      id: 'margarita_sa',
      name: 'Margarita (Sin Alcohol)',
      price: 400,
      emoji: '<:Margarita:1520043277292929114>',
      menuEmoji: '🍸',
      description: 'Tequila sustituido por buenas intenciones y mucha lima.',
      stock: 100,
      maxStock: 100,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 240,
      useMessage: 'La Margarita sin alcohol es casi igual de buena. Casi. Pero conduces mejor.'
    },
    'caipirinha_sa': {
      id: 'caipirinha_sa',
      name: 'Caipirinha (Sin Alcohol)',
      price: 450,
      emoji: '<:Caipirinha:1520043159114223727>',
      menuEmoji: '🥃',
      description: 'Lima, azúcar y agua con gas. Perfecta para el día siguiente.',
      stock: 90,
      maxStock: 90,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 270,
      useMessage: 'Bebes la Caipirinha sin alcohol. La lima te hace una pedorreta. Refrescante.'
    },
    'pina_colada_sa': {
      id: 'pina_colada_sa',
      name: 'Piña Colada (Sin Alcohol)',
      price: 500,
      emoji: '<:PinaColada:1520042823095685160>',
      menuEmoji: '🥥',
      description: 'Piña, coco y crema. Vacaciones sin resaca.',
      stock: 80,
      maxStock: 80,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 300,
      useMessage: 'La Piña Colada sin alcohol sabe a paraíso sin la resaca del paraíso.'
    },
    'mojito_sa': {
      id: 'mojito_sa',
      name: 'Mojito (Sin Alcohol)',
      price: 450,
      emoji: '<:Mohito:1520042750106402967>',
      menuEmoji: '🍃',
      description: 'Hierbabuena, lima y soda. Todo el refresco, ninguna mala decisión.',
      stock: 90,
      maxStock: 90,
      category: 'cocktail',
      usable: true,
      sellable: true,
      sellPrice: 270,
      useMessage: 'El Mojito sin alcohol es pura frescura. La hierbabuena te limpia el alma.'
    },
    'helado_vainilla': {
      id: 'helado_vainilla',
      name: 'Helado de Vainilla',
      price: 90,
      emoji: '<:HeladoVainilla:1520096905479192586>',
      menuEmoji: '🍦',
      description: 'Clásico, cremoso y sin sorpresas. Como Biel los domingos.',
      stock: 500,
      maxStock: 500,
      category: 'helado',
      usable: true,
      sellable: true,
      sellPrice: 54,
      useMessage: 'El Helado de Vainilla se derrite en tu lengua. Clásico, sencillo, perfecto.'
    },
    'helado_chocolate': {
      id: 'helado_chocolate',
      name: 'Helado de Chocolate',
      price: 90,
      emoji: '<:HeladoChoco:1520096742530486353>',
      menuEmoji: '🍫',
      description: 'Para los que saben que el chocolate lo arregla todo.',
      stock: 500,
      maxStock: 500,
      category: 'helado',
      usable: true,
      sellable: true,
      sellPrice: 54,
      useMessage: 'El Helado de Chocolate es pecaminoso. Cada cucharada es un billete de ida al cielo.'
    },
    'helado_fresa': {
      id: 'helado_fresa',
      name: 'Helado de Fresa',
      price: 100,
      emoji: '<:HeladoFresa:1520096865129857124>',
      menuEmoji: '🍓',
      description: 'Rosa, dulce y peligroso para la camiseta blanca.',
      stock: 450,
      maxStock: 450,
      category: 'helado',
      usable: true,
      sellable: true,
      sellPrice: 60,
      useMessage: 'Lames el Helado de Fresa. Es rosa, dulce, y te mancha la sonrisa.'
    },
    'helado_limon': {
      id: 'helado_limon',
      name: 'Helado de Limón',
      price: 100,
      emoji: '<:HeladoLimon:1520097096743518420>',
      menuEmoji: '🍋',
      description: 'Ácido, refrescante y con más actitud que el capitán.',
      stock: 450,
      maxStock: 450,
      category: 'helado',
      usable: true,
      sellable: true,
      sellPrice: 60,
      useMessage: 'El Helado de Limón te despierta el paladar. Ácido y refrescante como la vida misma.'
    },
    'helado_menta_chocolate': {
      id: 'helado_menta_chocolate',
      name: 'Helado de Menta y Chocolate',
      price: 120,
      emoji: '<:HeladoMentayChoco:1520096803087843578>',
      menuEmoji: '🌿',
      description: 'O lo amas o lo odias. No hay término medio.',
      stock: 350,
      maxStock: 350,
      category: 'helado',
      usable: true,
      sellable: true,
      sellPrice: 72,
      useMessage: 'El contraste de la menta y el chocolate te hace preguntarte por qué no comiste esto antes.'
    },
    'helado_cookies': {
      id: 'helado_cookies',
      name: 'Helado de Cookies',
      price: 130,
      emoji: '<:HeladoCookies:1520096623240155378>',
      menuEmoji: '🍪',
      description: 'Galletas dentro de helado. Innovación del BSC Bilel.',
      stock: 350,
      maxStock: 350,
      category: 'helado',
      usable: true,
      sellable: true,
      sellPrice: 78,
      useMessage: 'El Helado de Cookies cruje con cada cucharada. Galleta y helado, la pareja perfecta.'
    },
    'helado_mango': {
      id: 'helado_mango',
      name: 'Helado de Mango',
      price: 140,
      emoji: '<:HeladoMango:1520096958243410091>',
      menuEmoji: '🥭',
      description: 'Sabor tropical para sobrevivir al calor de cubierta.',
      stock: 300,
      maxStock: 300,
      category: 'helado',
      usable: true,
      sellable: true,
      sellPrice: 84,
      useMessage: 'El Helado de Mango sabe a trópico. Cierras los ojos y estás en una hamaca.'
    },
    'helado_coco': {
      id: 'helado_coco',
      name: 'Helado de Coco',
      price: 140,
      emoji: '<:HeladoCoco:1520096680702116080>',
      menuEmoji: '🥥',
      description: 'Cremoso, tropical y con tropezones de coco que te pillan desprevenido.',
      stock: 300,
      maxStock: 300,
      category: 'helado',
      usable: true,
      sellable: true,
      sellPrice: 84,
      useMessage: 'El Helado de Coco te transporta a una playa desierta. Cremoso, dulce, hipnótico.'
    },
    'helado_pistacho': {
      id: 'helado_pistacho',
      name: 'Helado de Pistacho',
      price: 150,
      emoji: '<:HeladoPistacho:1520097247826804754>',
      menuEmoji: '🍦',
      description: 'El sabor más controvertido del barco. O lo amas o lo odias.',
      stock: 250,
      maxStock: 250,
      category: 'helado',
      usable: true,
      sellable: true,
      sellPrice: 90,
      useMessage: 'El Helado de Pistacho divide opiniones. La tuya es clara: es el mejor de todos.'
    },
    'chaleco_salvavidas': {
      id: 'chaleco_salvavidas',
      name: 'Chaleco Salvavidas',
      price: 500,
      emoji: '🛟',
      description: 'Por si alguien te tira por la borda.',
      stock: 50,
      maxStock: 50,
      category: 'supervivencia',
      usable: true,
      sellable: true,
      sellPrice: 300,
      useMessage: 'Te pones el chaleco salvavidas. Por si alguien te tira por la borda, al menos flotas con estilo.'
    },
    'crema_solar_bsc': {
      id: 'crema_solar_bsc',
      name: 'Crema Solar BSC',
      price: 750,
      emoji: '🧴',
      description: 'Protección 50 contra los quemados del chat.',
      stock: 40,
      maxStock: 40,
      category: 'supervivencia',
      usable: true,
      sellable: true,
      sellPrice: 450,
      useMessage: 'Te untas la Crema Solar BSC. Tu piel ahora brilla más que el chat a las 3 de la mañana.'
    },
    'chanclas_buffet': {
      id: 'chanclas_buffet',
      name: 'Chanclas del Buffet',
      price: 1000,
      emoji: '🩴',
      description: 'Huele a gambas pero son icónicas.',
      stock: 35,
      maxStock: 35,
      category: 'supervivencia',
      usable: true,
      sellable: true,
      sellPrice: 600,
      useMessage: 'Calzas las Chanclas del Buffet. Huele a gambas, pero ya eres leyenda.'
    },
    'mojito_cubierta': {
      id: 'mojito_cubierta',
      name: 'Mojito de Cubierta',
      price: 1500,
      emoji: '🍹',
      description: 'Te emborracha lo justo.',
      stock: 60,
      maxStock: 60,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 900,
      useMessage: 'Bebes un Mojito de Cubierta. El viento, el mar y una leve pérdida de equilibrio.'
    },
    'buffet_ilimitado': {
      id: 'buffet_ilimitado',
      name: 'Buffet Ilimitado',
      price: 2500,
      emoji: '🍽️',
      description: 'Come todo lo que puedas.',
      stock: 30,
      maxStock: 30,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 1500,
      useMessage: 'Atacas el Buffet Ilimitado. Sales rodando, pero feliz.'
    },
    'botella_ron_capitán': {
      id: 'botella_ron_capitán',
      name: 'Botella de Ron del Capitán',
      price: 7000,
      emoji: '🍾',
      description: '90% Coca-Cola, etiqueta molona.',
      stock: 12,
      maxStock: 12,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 4200,
      useMessage: 'Abres la Botella de Ron del Capitán. 90% Coca-Cola, 100% arrepentimiento mañana.'
    },
    'bk_whopper': {
      id: 'bk_whopper',
      name: 'Whopper',
      price: 200,
      emoji: '<:BK_Whopper:1520100389658038272>',
      description: 'La hamburguesa que desafió a la ley seca del barco. Carne a la parrilla y remordimientos aparte.',
      stock: 200,
      maxStock: 200,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 120,
      useMessage: 'Devoras el Whopper con furia. El capitán Biel aplaude desde lejos.'
    },
    'bk_double_cheeseburger': {
      id: 'bk_double_cheeseburger',
      name: 'Doble Cheeseburger',
      price: 160,
      emoji: '<:BK_DoubleCheeseburger:1520100503395111002>',
      description: 'Doble carne, doble queso, doble arrepentimiento. Todo el sabor del BSC Bilel en cada mordisco.',
      stock: 180,
      maxStock: 180,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 96,
      useMessage: 'Atacas la Doble Cheeseburger. El colesterol sube, la felicidad también.'
    },
    'bk_king_chicken_fries': {
      id: 'bk_king_chicken_fries',
      name: 'King Chicken Fries',
      price: 130,
      emoji: '<:BK_KingChickenFries:1520100626795597865>',
      description: 'Tiras de pollo empanadas con forma de patata frita. La identidad culinaria es confusa pero el sabor es real.',
      stock: 250,
      maxStock: 250,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 78,
      useMessage: 'Crujes las King Chicken Fries. Son pollo, son patatas, son todo lo que está bien.'
    },
    'bk_patatas_fritas_grandes': {
      id: 'bk_patatas_fritas_grandes',
      name: 'Patatas Fritas Grandes',
      price: 80,
      emoji: '<:BK_PatatasFritasGrandes:1520100552053096559>',
      description: 'Patatas crujientes para compartir. O para no compartir. No juzgamos tu egoísmo.',
      stock: 300,
      maxStock: 300,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 48,
      useMessage: 'Las patatas están en su punto justo de sal. Perfectas.'
    },
    'bk_cheesecake': {
      id: 'bk_cheesecake',
      name: 'Cheesecake',
      price: 110,
      emoji: '<:BK_Cheesecake:1520100438802694254>',
      description: 'Tarta de queso cremosa que casi justifica el viaje en crucero. Casi.',
      stock: 120,
      maxStock: 120,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 66,
      useMessage: 'El Cheesecake se deshace en tu boca. Por un momento olvidas que estás en alta mar sin cobertura.'
    },
    'bk_oreo_milkshake': {
      id: 'bk_oreo_milkshake',
      name: 'Oreo Milkshake',
      price: 100,
      emoji: '<:BK_OreoMilkshake:1520105093393813737>',
      description: 'Batido cremoso con trocitos de galleta Oreo. Mejor que el amor, más duradero que el wifi del barco.',
      stock: 150,
      maxStock: 150,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 60,
      useMessage: 'Bebes el Oreo Milkshake y sientes cómo la felicidad recorre tu garganta. Es espeso, es pecaminoso, es perfecto.'
    },
    'kfc_bucket_de_alitas': {
      id: 'kfc_bucket_de_alitas',
      name: 'Bucket de Alitas',
      price: 250,
      emoji: '<:KFC_BucketDeAlitas:1520103267278000190>',
      description: 'Un cubo entero de alitas bañadas en la receta secreta de los 11 herbivorales. Adictivas y sin juicio.',
      stock: 100,
      maxStock: 100,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 150,
      useMessage: 'Abrir el Bucket de Alitas es como abrir la caja de Pandora, pero con más salsa BBQ y menos esperanzas rotas.'
    },
    'kfc_chicken_sandwich': {
      id: 'kfc_chicken_sandwich',
      name: 'Chicken Sandwich',
      price: 170,
      emoji: '<:KFC_ChickenSandwich:1520103391894700222>',
      description: 'Pechuga de pollo empanada con pan brioche y pepinillos. La competencia llora en cubierta.',
      stock: 150,
      maxStock: 150,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 102,
      useMessage: 'El Chicken Sandwich cruje al morderlo. El pollo está tan jugoso que debería ser ilegal.'
    },
    'kfc_popcorn_chicken': {
      id: 'kfc_popcorn_chicken',
      name: 'Popcorn Chicken',
      price: 140,
      emoji: '<:KFC_PopcornChicken:1520102674198958100>',
      description: 'Bocados de pollo rebozado del tamaño de un mordisco. Ideales para comer mientras miras el horizonte.',
      stock: 200,
      maxStock: 200,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 84,
      useMessage: 'Te zampas el Popcorn Chicken a puñados como si no hubiera un mañana. Delicioso y socialmente aceptable.'
    },
    'kfc_pure_de_patatas': {
      id: 'kfc_pure_de_patatas',
      name: 'Puré de Patatas',
      price: 70,
      emoji: '<:KFC_PureDePatatas:1520102929564962948>',
      description: 'Puré cremoso con su salsa secreta. La comida de la abuela que nunca tuviste en el BSC Bilel.',
      stock: 200,
      maxStock: 200,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 42,
      useMessage: 'El Puré de Patatas te transporta a la infancia. O a lo que imaginas que era tener una abuela que cocinara.'
    },
    'kfc_brownie': {
      id: 'kfc_brownie',
      name: 'Brownie',
      price: 95,
      emoji: '<:KFC_Brownie:1520103453404434465>',
      description: 'Brownie de chocolate intenso con nueces. Pequeño pero letal para la dieta del crucero.',
      stock: 150,
      maxStock: 150,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 57,
      useMessage: 'El Brownie está caliente y pegajoso. El chocolate se derrite en tu boca. Valió cada gramo de culpa.'
    },
    'dom_pepperoni_pizza': {
      id: 'dom_pepperoni_pizza',
      name: 'Pizza Pepperoni',
      price: 220,
      emoji: '<:DOM_PepperoniPizza:1520105153435406499>',
      description: 'Pepperoni clásico con queso fundido. La reina de las pizzas, intocable e indiscutible.',
      stock: 100,
      maxStock: 100,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 132,
      useMessage: 'La Pizza Pepperoni llega caliente. El queso se estira hasta el infinito. Perfecta.'
    },
    'dom_bbq_chicken_pizza': {
      id: 'dom_bbq_chicken_pizza',
      name: 'Pizza BBQ Chicken',
      price: 250,
      emoji: '<:DOM_BBQChickenPizza:1520105213711749343>',
      description: 'Pollo, cebolla, salsa BBQ y queso. La combinación que hace llorar a los italianos de felicidad.',
      stock: 80,
      maxStock: 80,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 150,
      useMessage: 'La Pizza BBQ Chicken tiene el punto justo de ahumado. La cebolla cruje, el pollo canta.'
    },
    'dom_cheesy_bread': {
      id: 'dom_cheesy_bread',
      name: 'Cheesy Bread',
      price: 120,
      emoji: '<:DOM_CheesyBread:1520105293873152143>',
      description: 'Pan relleno de mozzarella con ajo y hierbas. El acompañante perfecto para cualquier pizza.',
      stock: 180,
      maxStock: 180,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 72,
      useMessage: 'Partes el Cheesy Bread y el queso se derrama. Es un desastre, pero un desastre hermoso.'
    },
    'dom_alitas_bbq': {
      id: 'dom_alitas_bbq',
      name: 'Alitas BBQ',
      price: 190,
      emoji: '<:DOM_AlitasBBQ:1520105377943912458>',
      description: 'Alitas bañadas en salsa BBQ ahumada. La competencia directa del KFC en el barco.',
      stock: 120,
      maxStock: 120,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 114,
      useMessage: 'Las Alitas BBQ están tan buenas que te lames los dedos sin pudor. Y los de al lado también.'
    },
    'dom_cookie_dough': {
      id: 'dom_cookie_dough',
      name: 'Cookie Dough',
      price: 100,
      emoji: '<:DOM_CookieDough:1520105671809306715>',
      description: 'Masa de galleta horneada con trozos de chocolate. Mejor que la mayoría de las decisiones de tu vida.',
      stock: 130,
      maxStock: 130,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 60,
      useMessage: 'El Cookie Dough está blandito por dentro y crujiente por fuera. Una obra maestra.'
    },
    'sb_caramel_frappuccino': {
      id: 'sb_caramel_frappuccino',
      name: 'Caramel Frappuccino',
      price: 140,
      emoji: '<:SB_CaramelFrappuccino:1520107834447102084>',
      description: 'Bebida fría de caramelo con nata montada. Más cara que tu primer coche, pero más rica.',
      stock: 150,
      maxStock: 150,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 84,
      useMessage: 'Bebes el Caramel Frappuccino. Tu nombre está mal escrito en el vaso, pero te da igual.'
    },
    'sb_latte_macchiato': {
      id: 'sb_latte_macchiato',
      name: 'Latte Macchiato',
      price: 110,
      emoji: '<:SB_LatteMacchiato:1520107431818952855>',
      description: 'Café con leche de los que saben. Vuelve a casa por Navidad y también en el BSC Bilel.',
      stock: 200,
      maxStock: 200,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 66,
      useMessage: 'El Latte Macchiato está en su punto. El café te despierta el alma.'
    },
    'sb_smoothie_de_fresa': {
      id: 'sb_smoothie_de_fresa',
      name: 'Smoothie de Fresa',
      price: 120,
      emoji: '<:SB_SmoothieDeFresa:1520107098455933028>',
      description: 'Batido de fresa natural con yogur. Saludable sobre el papel, delicioso en la práctica.',
      stock: 160,
      maxStock: 160,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 72,
      useMessage: 'El Smoothie de Fresa es fresco y afrutado. Casi te sientes saludable.'
    },
    'sb_muffin_de_arandanos': {
      id: 'sb_muffin_de_arandanos',
      name: 'Muffin de Arándanos',
      price: 85,
      emoji: '<:SB_MuffinDeArandanos:1520107327028592650>',
      description: 'Muffin esponjoso con arándanos reales. Acompañante perfecto para tu café mañanero.',
      stock: 130,
      maxStock: 130,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 51,
      useMessage: 'El Muffin de Arándanos está esponjoso y lleno de fruta. El desayuno perfecto.'
    },
    'sb_chocolate_cookie': {
      id: 'sb_chocolate_cookie',
      name: 'Chocolate Cookie',
      price: 75,
      emoji: '<:SB_ChocolateCookie:1520107757838274780>',
      description: 'Galleta de chocolate gigante. Blandita por dentro, crujiente por fuera. Adictiva.',
      stock: 180,
      maxStock: 180,
      category: 'gastronomia',
      usable: true,
      sellable: true,
      sellPrice: 45,
      useMessage: 'La Chocolate Cookie se deshace en tu boca. Pides otra sin pensarlo.'
    },
    'ticket_bingo': {
      id: 'ticket_bingo',
      name: 'Ticket de Bingo',
      price: 1750,
      emoji: '🎫',
      description: 'No ganas pero gritas línea.',
      stock: 45,
      maxStock: 45,
      category: 'entretenimiento',
      usable: true,
      sellable: true,
      sellPrice: 1050,
      useMessage: 'Usas tu Ticket de Bingo. No ganas, pero gritas línea y te echan.'
    },
    'ficha_casino': {
      id: 'ficha_casino',
      name: 'Ficha de Casino',
      price: 2000,
      emoji: '🎰',
      description: 'Apuéstala o guárdala.',
      stock: 80,
      maxStock: 80,
      category: 'entretenimiento',
      usable: true,
      sellable: true,
      sellPrice: 1200,
      useMessage: 'Apuestas tu Ficha de Casino. La suerte sonríe... o no.'
    },
    'microfono_karaoke': {
      id: 'microfono_karaoke',
      name: 'Micrófono de Karaoke',
      price: 3000,
      emoji: '🎤',
      description: 'Con derecho a arruinar una canción.',
      stock: 20,
      maxStock: 20,
      category: 'entretenimiento',
      usable: true,
      sellable: true,
      sellPrice: 1800,
      useMessage: 'Coges el Micrófono de Karaoke. Una canción destrozada, un público traumatizado.'
    },
    'disfraz_marinero': {
      id: 'disfraz_marinero',
      name: 'Disfraz de Marinero',
      price: 3500,
      emoji: '🎭',
      description: 'Para ligar mal y parecer ridículo.',
      stock: 25,
      maxStock: 25,
      category: 'entretenimiento',
      usable: true,
      sellable: true,
      sellPrice: 2100,
      useMessage: 'Te pones el Disfraz de Marinero. Ligas mal, pero pareces ridículo con convicción.'
    },
    'loro_cubierta': {
      id: 'loro_cubierta',
      name: 'Loro de Cubierta',
      price: 4000,
      emoji: '🦜',
      description: 'Repite tus errores en bucle.',
      stock: 10,
      maxStock: 10,
      category: 'entretenimiento',
      usable: true,
      sellable: true,
      sellPrice: 2400,
      useMessage: 'Sacas el Loro de Cubierta. Repite todos tus errores en bucle. Como tu ex.'
    },
    'gorra_capitán': {
      id: 'gorra_capitán',
      name: 'Gorra de Capitán',
      price: 1250,
      emoji: '🧢',
      description: 'Te la pones y dejas de obedecer a Biel.',
      stock: 30,
      maxStock: 30,
      category: 'merchandising',
      usable: true,
      sellable: true,
      sellPrice: 750,
      useMessage: 'Te pones la Gorra de Capitán. A partir de ahora, Biel es tu subordinado.'
    },
    'foto_biel': {
      id: 'foto_biel',
      name: 'Foto con Biel',
      price: 4500,
      emoji: '📸',
      description: 'Edición limitada, fondo verde.',
      stock: 15,
      maxStock: 15,
      category: 'merchandising',
      usable: true,
      sellable: true,
      sellPrice: 2700,
      useMessage: 'Enmarcaste la Foto con Biel. Edición limitada, fondo verde, vergüenza infinita.'
    },
    'traje_gala': {
      id: 'traje_gala',
      name: 'Traje de Gala',
      price: 6000,
      emoji: '🎩',
      description: 'Obligatorio para cenas que nadie se toma en serio.',
      stock: 18,
      maxStock: 18,
      category: 'merchandising',
      usable: true,
      sellable: true,
      sellPrice: 3600,
      useMessage: 'Te vistes con el Traje de Gala. Cena elegante que nadie se toma en serio.'
    },
    'wifi_premium': {
      id: 'wifi_premium',
      name: 'WiFi Premium',
      price: 5000,
      emoji: '🛜',
      description: 'Funciona 10 minutos seguidos.',
      stock: 15,
      maxStock: 15,
      category: 'lujo',
      usable: true,
      sellable: true,
      sellPrice: 3000,
      useMessage: 'Conectas el WiFi Premium. Funciona diez minutos seguidos. Récord.'
    },
    'masaje_spa': {
      id: 'masaje_spa',
      name: 'Masaje en el Spa',
      price: 5500,
      emoji: '🧖',
      description: 'Te relaja hasta que alguien mencione política.',
      stock: 12,
      maxStock: 12,
      category: 'lujo',
      usable: true,
      sellable: true,
      sellPrice: 3300,
      useMessage: 'Disfrutas del Masaje en el Spa. Te relajas hasta que alguien menciona política.'
    },
    'excursion_lancha': {
      id: 'excursion_lancha',
      name: 'Excursión en Lancha',
      price: 7500,
      emoji: '🛥️',
      description: 'Sales 20 minutos y te pierdes.',
      stock: 8,
      maxStock: 8,
      category: 'lujo',
      usable: true,
      sellable: true,
      sellPrice: 4500,
      useMessage: 'Sales en Excursión en Lancha. Veinte minutos después estás perdido.'
    },
    'jacuzzi_privado': {
      id: 'jacuzzi_privado',
      name: 'Jacuzzi Privado',
      price: 8500,
      emoji: '🛁',
      description: 'Capacidad para dos, entran siete.',
      stock: 6,
      maxStock: 6,
      category: 'lujo',
      usable: true,
      sellable: true,
      sellPrice: 5100,
      useMessage: 'Reservas el Jacuzzi Privado. Capacidad para dos, entran siete. Fiesta.'
    },
    'upgrade_camarote': {
      id: 'upgrade_camarote',
      name: 'Upgrade de Camarote',
      price: 10000,
      emoji: '🛏️',
      description: 'Ahora tienes ventana. Sigue oliendo a motor.',
      stock: 5,
      maxStock: 5,
      category: 'lujo',
      usable: true,
      sellable: true,
      sellPrice: 6000,
      useMessage: 'Consigues el Upgrade de Camarote. Ahora tienes ventana. Sigue oliendo a motor.'
    },
    'mapa_tesoro': {
      id: 'mapa_tesoro',
      name: 'Mapa del Tesoro',
      price: 6500,
      emoji: '🗺️',
      description: 'Lleva a la caja fuerte vacía del casino.',
      stock: 7,
      maxStock: 7,
      category: 'exclusivo',
      usable: true,
      sellable: true,
      sellPrice: 3900,
      useMessage: 'Sigues el Mapa del Tesoro. Lleva a la caja fuerte vacía del casino. Biel se ríe.'
    },
    'subasta_arte_barco': {
      id: 'subasta_arte_barco',
      name: 'Subasta de Arte del Barco',
      price: 12500,
      emoji: '🎨',
      description: 'Cuadro feo firmado por Biel.',
      stock: 3,
      maxStock: 3,
      category: 'exclusivo',
      usable: true,
      sellable: true,
      sellPrice: 7500,
      useMessage: 'Ganas la Subasta de Arte del Barco. Cuadro feo firmado por Biel. Invierno en el salón.'
    },
    'cena_capitán': {
      id: 'cena_capitán',
      name: 'Cena con el Capitán',
      price: 15000,
      emoji: '🍽️',
      description: 'Él habla, tú asientes. Tres horas.',
      stock: 3,
      maxStock: 3,
      category: 'exclusivo',
      usable: true,
      sellable: true,
      sellPrice: 9000,
      useMessage: 'Asistes a la Cena con el Capitán. Él habla, tú asientes. Tres horas eternas.'
    },
    'tour_puente_mando': {
      id: 'tour_puente_mando',
      name: 'Tour por el Puente de Mando',
      price: 18000,
      emoji: '🧭',
      description: 'Descubres que nadie sabe dónde vamos.',
      stock: 2,
      maxStock: 2,
      category: 'exclusivo',
      usable: true,
      sellable: true,
      sellPrice: 10800,
      useMessage: 'Haces el Tour por el Puente de Mando. Descubres que nadie sabe dónde vamos.'
    },
    'llave_barco': {
      id: 'llave_barco',
      name: 'Llave del Barco',
      price: 22000,
      emoji: '⚓',
      description: 'No arranca nada, pero te sientes importante.',
      stock: 1,
      maxStock: 1,
      category: 'exclusivo',
      usable: true,
      sellable: true,
      sellPrice: 13200,
      useMessage: 'Usas la Llave del Barco. No arranca nada, pero te sientes importante.'
    },
    'yate_privado_bsc': {
      id: 'yate_privado_bsc',
      name: 'Yate Privado BSC',
      price: 50000,
      emoji: '🚢',
      description: 'Flex supremo. Miras por encima del hombro a los turistas.',
      stock: 1,
      maxStock: 1,
      category: 'exclusivo',
      usable: true,
      sellable: true,
      sellPrice: 30000,
      useMessage: 'Subes a tu Yate Privado BSC. Flex supremo. Miras por encima del hombro a los turistas.'
    }
  }
};

function load() {
  if (!fs.existsSync(dbPath)) {
    return structuredClone(defaultData);
  }
  try {
    const data = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
    const base = structuredClone(defaultData);

    // Fusionar usuarios
    if (data.users) {
      for (const [userId, userData] of Object.entries(data.users)) {
        base.users[userId] = { ...base.users[userId], ...userData };
      }
    }

    // Fusionar items: default añade nuevos, disco conserva stock/precio si existe
    if (data.items) {
      for (const [itemId, diskItem] of Object.entries(data.items)) {
        if (base.items[itemId]) {
          base.items[itemId] = { ...base.items[itemId], ...diskItem };
        } else {
          base.items[itemId] = diskItem;
        }
      }
    }

    // Asegurar que los items por defecto heredan campos nuevos si faltan en disco
    for (const [itemId, defaultItem] of Object.entries(defaultData.items)) {
      if (base.items[itemId]) {
        base.items[itemId] = { ...defaultItem, ...base.items[itemId] };
      }
    }

    return base;
  } catch (error) {
    console.error('Error al cargar la base de datos:', error);
    return structuredClone(defaultData);
  }
}

function save(data) {
  fs.writeFileSync(dbPath, JSON.stringify(data, null, 2), 'utf8');
}

function getUser(data, userId) {
  if (!data.users[userId]) {
    data.users[userId] = {
      balance: 0,
      bank: 0,
      inventory: {},
      dailyStreak: 0,
      lastDaily: null,
      lastWork: null,
      lastCrime: null,
      lastRob: null,
      lastExcursion: null,
      passPlan: 'basic',
      passExpiresAt: null,
      passAutoRenew: false,
      passLastChargeAt: null,
      passIncludedDrinks: {}
    };
  }
  return data.users[userId];
}

module.exports = { load, save, getUser, defaultData };
